---
title: "differential analysis on omics data across timepoints"
author: "Shilin"
date: "2022-10-10"
output: html_document
---
#Package library
```{r} 
library(gtools)
library(pls)
library(sgof)
library(data.table)
library(dplyr)
library(ggpubr)
library(tibble)
library(tidyverse)
library(Biobase)
library(BiocParallel)
library(sva)
#library(bladderbatch)
#library(snpStats)
library(data.table)
library("ggplot2")
library("gridExtra")
library("edgeR")
library("UpSetR")
library(data.table)
library(openxlsx)
library(ggrepel)
```
#Load data
```{r}
load("~/df_omics.RData")

df_outcome <- read_excel("~/df.outcome.xlsx")

```
#Omics in BNT
##Lipidomics 
###Mixed model
```{r}

#Lipdomics data

data_by_vaccine <- list()
marker_names<-names(df_lip_overall)[-c(1:5,184:185)]
addq <- function(x) paste0("`", x, "`")

for (vaccine_group in c("B", "S")) {

  df_vaccine <- df_lip_overall %>% 
    filter(vaccine==vaccine_group) %>% 
    filter(time!="QA") %>% 
    filter(time!="QC") 
  names(df_vaccine)[5]<-"group"

  df_vaccine$group <- factor(df_vaccine$group,
                             labels = c("M0", "M1", "M6"),
                             levels = c("PRE", "M1", "M6"))
  

  result_lme <- list()
  

  for (i in seq_along(marker_names)) {
    marker <- marker_names[i]
   
    formula_baseline_m1 <- as.formula(paste0(marker, "~ group + Age +Gender"))
    print(formula_baseline_m1)

    model_baseline_m1 <- nlme::lme(formula_baseline_m1,control = lmeControl(opt = "optim"), random = ~1 | id, data = df_vaccine,na.action =na.omit )
    sum_mod <- summary(model_baseline_m1)
    sum_mod_dt <- data.frame(sum_mod$tTable)
    sum_mod_dt$Marker <- marker
    sum_mod_dt$Var <- rownames(sum_mod_dt)
    result_lme[[marker]] <- sum_mod_dt
  }

  data_by_vaccine[[vaccine_group]] <- result_lme
  result_lme_dt <- do.call("rbind", result_lme)
  names(result_lme_dt)[5] <- "pval"
  # Remove intercept
  result_lme_dt <- result_lme_dt[result_lme_dt$Var != "(Intercept)",]
  result_lme_dt <- result_lme_dt[result_lme_dt$Var %in% c("groupM1","groupM6"),]
  
  result_lme_dt$p_adj <- p.adjust(result_lme_dt$pval, method = "BH")
  result_lme_dt <- result_lme_dt[,c("Value","Marker","Var","pval","p_adj" )]
  result_lme_dt <- na.omit(result_lme_dt)
  dt_w <- reshape(result_lme_dt, idvar = "Marker", timevar = "Var", direction = "wide")
  
  dt_w$Marker_new[order(dt_w$Marker)]<-df_lip_overall_raw$LipidIon[order(df_lip_overall_raw$LipidIon)]
  rownames(dt_w) <- dt_w$Marker
  dt_w<-
    dt_w %>%
    merge(df_lip_overall_raw %>% dplyr::rename(Marker_new=LipidIon) %>% dplyr::select(Class,Marker_new),by="Marker_new")
 
  file_name <- paste("~/Differential_analysis_paired/Lipidomics/LMM_", vaccine_group, ".xlsx", sep = "")
   write.xlsx(dt_w, file = file_name)
}

```
##Metabolomics
###Mixed model
```{r}

data_by_vaccine <- list()
marker_names<-names(df_meta_overall)[-c(1:5)]

for (vaccine_group in c("B", "S")) {
  
    df_vaccine <- df_meta_overall %>% 
      filter(vaccine==vaccine_group) %>% 
      filter(time!="QA") 
    names(df_vaccine)[5]<-"group"
    
    df_vaccine$group <- factor(df_vaccine$group,
                               labels = c("M0", "M1", "M6"),
                               levels = c("PRE", "M1", "M6"))
   
    result_lme <- list()
    
   
    for (i in seq_along(marker_names)[1:2]) {
      marker <- marker_names[i]
      
     
      formula_baseline_m1 <- as.formula(paste(marker, "~ group + Age +Gender"))
      print(formula_baseline_m1)
      
      model_baseline_m1 <- nlme::lme(formula_baseline_m1, random = ~1 | id, data = df_vaccine)
      sum_mod <- summary(model_baseline_m1)
      sum_mod_dt <- data.frame(sum_mod$tTable)
      sum_mod_dt$Marker <- marker
      sum_mod_dt$Var <- rownames(sum_mod_dt)
      result_lme[[marker]] <- sum_mod_dt
    }
    
    data_by_vaccine[[vaccine_group]] <- result_lme
    result_lme_dt <- do.call("rbind", result_lme)
    names(result_lme_dt)[5] <- "pval"
    # Remove intercept
    result_lme_dt <- result_lme_dt[result_lme_dt$Var != "(Intercept)",]
    result_lme_dt <- result_lme_dt[result_lme_dt$Var %in% c("groupM1","groupM6"),]
    
    result_lme_dt$p_adj <- p.adjust(result_lme_dt$pval, method = "BH")
    result_lme_dt <- result_lme_dt[,c("Value","Marker","Var","pval","p_adj" )]
    result_lme_dt <- na.omit(result_lme_dt)
    dt_w <- reshape(result_lme_dt, idvar = "Marker", timevar = "Var", direction = "wide")
    #dt_w <- dt_w[,mixedsort(names(dt_w))]
    rownames(dt_w) <- dt_w$Marker
    dt_w<-dt_w %>% merge(df_metabolomic_raw %>% rename(Marker=HMDB_ID),by="Marker")

  
 
  file_name <- paste("~/Differential_analysis_paired/Metabolomics/LMM_", vaccine_group, ".xlsx", sep = "")
  write.xlsx(dt_w, file = file_name)
}
```
##Transcriptomics
```
library("BiocParallel")
# Specify parallel processing parameters
    # this is used implicitly by dream() to run in parallel
param <- SnowParam(64, "SOCK", progressbar = TRUE)

for (vaccine_types in c("BNT","SNV")){
  if(vaccine_types=="BNT") {
    df_rna_current=df_rna_bnt} else {df_rna_current=df_rna_snv}

   coldata_current <- data.frame(Time = factor(substr(names(df_rna_current), 7, 8)),
                                  sample = factor(substr(names(df_rna_current), 1, 5))) %>%
      mutate(subject_id = paste0(sample, "_", Time)) %>%
      merge(df_outcome %>% dplyr::select(batch,Subject_id,Age, Gender),by.x="sample",by.y="Subject_id")%>% 
      column_to_rownames("subject_id") %>%
      mutate(batch=as.factor(batch),
             Gender=as.factor(Gender))
    
    # Identify paired samples
    paired_samples <-
      table(coldata_current$sample, coldata_current$Time) 
    
    paired_sample_names <- rownames(paired_samples)[apply(paired_samples, 1, min) > 0]
    
    # Filter expression data using dplyr's select
    df_rna_current <- df_rna_current %>%
      dplyr::select(matches(paired_sample_names))
    
    # Filter coldata for paired samples
    coldata_current <- coldata_current %>%
      filter(sample %in% paired_sample_names) 
    
    df_rna_current<-df_rna_current[,match(rownames(coldata_current),names(df_rna_current))]
    gExpr=DGEList(df_rna_current)
    gExpr = calcNormFactors( gExpr )
    print(dim(gExpr$counts))

#Dream
    # The variable to be tested must be a fixed effect
    form <- ~ Time + Gender + Age+batch + (1 | sample)
    # estimate weights using linear mixed model of dream
    vobjDream <- voomWithDreamWeights(gExpr, form, coldata_current, BPPARAM = param)

    fitmm <- dream(vobjDream, form, coldata_current)
    fitmm <- eBayes(fitmm)
    res.current<-topTable(fitmm, coef=c("TimeM1","TimeM6"),n=Inf)
  
    
    res.current.df <- 
      data.frame(res.current, stringsAsFactors = FALSE, check.names = FALSE) %>%
      rename(padj=adj.P.Val,log2FoldChange=logFC)
   
    
    write.table(res.current.df, 
                paste0('~/M1_M0_Limma_Adjust_M6_M0_', vaccine_types,'.txt'), 
                col.names = NA, sep = '\t', quote = FALSE)
}

```


